load('config.js');
function execute() {
    return Response.success([
        {title: "Truyện mới cập nhật", input: BASE_URL + "/truyen-moi-cap-nhat", script: "gen.js"},
        {title: "Truyện Hot", input: BASE_URL + "/truyen-hot/", script: "gen.js"},
        {title: "Truyện Full", input: BASE_URL + "/truyen-full/", script: "gen.js"},
        {title: "Tiên Hiệp Hoàn", input: BASE_URL + "/truyen-tien-hiep/hoan/", script: "gen.js"},
        {title: "Kiếm Hiệp Hoàn", input: BASE_URL + "/truyen-kiem-hiep-hay/hoan/", script: "gen.js"},
        {title: "Ngôn Tình Hoàn", input: BASE_URL + "/truyen-ngon-tinh/hoan/", script: "gen.js"},
        {title: "Quan Trường Hoàn", input: BASE_URL + "/truyen-quan-truong/hoan/", script: "gen.js"},
        {title: "Xuyên Không Hoàn", input: BASE_URL + "/truyen-xuyen-khong/hoan/", script: "gen.js"},
        {title: "Trinh Thám Hoàn", input: BASE_URL + "/truyen-trinh-tham/hoan/", script: "gen.js"},
        {title: "Thám Hiểm Hoàn", input: BASE_URL + "/truyen-tham-hiem/hoan/", script: "gen.js"},
        {title: "Linh Dị Hoàn", input: BASE_URL + "/truyen-linh-di/hoan/", script: "gen.js"},
        {title: "Ngược Hoàn", input: BASE_URL + "/truyen-nguoc/hoan/", script: "gen.js"},
        {title: "Sủng Hoàn", input: BASE_URL + "/truyen-sung/hoan/", script: "gen.js"},
        {title: "Cung Đấu Hoàn", input: BASE_URL + "/truyen-cung-dau/hoan/", script: "gen.js"},
        {title: "Nữ Cường Hoàn", input: BASE_URL + "/truyen-nu-cuong/hoan/", script: "gen.js"},
        {title: "Đông Phương Hoàn", input: BASE_URL + "/truyen-dong-phuong/hoan/", script: "gen.js"},
        {title: "Đam Mỹ Hoàn", input: BASE_URL + "/truyen-dam-my/hoan/", script: "gen.js"},
        {title: "Bách Hợp Hoàn", input: BASE_URL + "/truyen-bach-hop/hoan/", script: "gen.js"},
        {title: "Hài Hước Hoàn", input: BASE_URL + "/truyen-hai-huoc/hoan/", script: "gen.js"},
        {title: "Cổ Đại Hoàn", input: BASE_URL + "/truyen-co-dai/hoan/", script: "gen.js"},
        {title: "Mạt Thế Hoàn", input: BASE_URL + "/truyen-mat-the/hoan/", script: "gen.js"},
        {title: "Tiểu Thuyết Hoàn", input: BASE_URL + "/truyen-tieu-thuyet/hoan/", script: "gen.js"},
        {title: "Khác Hoàn", input: BASE_URL + "/truyen-khac/hoan/", script: "gen.js"},
        {title: "Võng Du Hoàn", input: BASE_URL + "/truyen-vong-du/hoan/", script: "gen.js"},
        {title: "Khoa Huyễn Hoàn", input: BASE_URL + "/truyen-khoa-huyen/hoan/", script: "gen.js"},
        {title: "Dị Năng Hoàn", input: BASE_URL + "/truyen-di-nang/hoan/", script: "gen.js"},
        {title: "Huyền Huyễn Hoàn", input: BASE_URL + "/truyen-huyen-huyen/hoan/", script: "gen.js"},
        {title: "Trọng Sinh Hoàn", input: BASE_URL + "/truyen-trong-sinh/hoan/", script: "gen.js"},
        {title: "Đô Thị Hoàn", input: BASE_URL + "/truyen-do-thi/hoan/", script: "gen.js"},
        {title: "Dị Giới Hoàn", input: BASE_URL + "/truyen-di-gioi/hoan/", script: "gen.js"},
        {title: "Gia Đấu Hoàn", input: BASE_URL + "/truyen-gia-dau/hoan/", script: "gen.js"},
        {title: "Điền Văn Hoàn", input: BASE_URL + "/truyen-dien-van/hoan/", script: "gen.js"},
        {title: "Nữ Phụ Hoàn", input: BASE_URL + "/truyen-nu-phu/hoan/", script: "gen.js"},
        {title: "Quân Sự Hoàn", input: BASE_URL + "/truyen-quan-su/hoan/", script: "gen.js"},
        {title: "Lịch Sử Hoàn", input: BASE_URL + "/truyen-lich-su/hoan/", script: "gen.js"},
        {title: "Truyện Teen Hoàn", input: BASE_URL + "/truyen-teen/hoan/", script: "gen.js"},
        {title: "Light Novel Hoàn", input: BASE_URL + "/truyen-light-novel/hoan/", script: "gen.js"},
        {title: "Đoản Văn Hoàn", input: BASE_URL + "/truyen-doan-van/hoan/", script: "gen.js"},
        {title: "Việt Nam Hoàn", input: BASE_URL + "/truyen-viet-nam/hoan/", script: "gen.js"},
        {title: "Dã Sử Hoàn", input: BASE_URL + "/truyen-da-su/hoan/", script: "gen.js"},
        {title: "Phương Tây Hoàn", input: BASE_URL + "/truyen-phuong-tay/hoan/", script: "gen.js"},
        {title: "Hệ Thống Hoàn", input: BASE_URL + "/truyen-he-thong/hoan/", script: "gen.js"},
        {title: "Xuyên Nhanh Hoàn", input: BASE_URL + "/truyen-xuyen-nhanh/hoan/", script: "gen.js"},
        {title: "Hiện Đại Hoàn", input: BASE_URL + "/truyen-hien-dai/hoan/", script: "gen.js"},
        {title: "Tổng tài Hoàn", input: BASE_URL + "/truyen-tong-tai/hoan/", script: "gen.js"}
    ]);
}
